# Generated by Django 5.2.5 on 2025-08-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Music', 'Music'), ('Business', 'Business'), ('Food', 'Food')], default='Technology', max_length=50),
        ),
    ]
